Pastel/Web/Pastelaria.Web/Controllers/LoginController.cs
using Pastelaria.Web.Infra; 
using System.Web.Mvc; 
namespace Pastelaria.Web.Controllers
{
    public class LoginController : BaseController
    {
        // GET: Login
        public ActionResult Index()
        {
            return View(); // Retorna a view associada ao método Index(), normalmente representando a página de login.
        }
    }
}

Pastel/Web/Pastelaria.Web/Controllers/SobreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pastelaria.Web.Controllers
{
    [Authorize]
    public class SobreController : Controller
    {
        // GET: Sobre
        public ActionResult Index()
        {
            return View();
        }
    }
}

Pastel/Web/Pastelaria.Web/Controllers/TarefaController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Pastelaria.Web.Application.Tarefa;
using Pastelaria.Web.Application.Tarefa.Model;
using Pastelaria.Web.Infra;

namespace Pastelaria.Web.Controllers
{
    [Authorize]
    public class TarefaController : BaseController
    {
        // Instâncias das aplicações e serviços injetados no controlador
        private readonly TarefaApplication _tarefaApplication;
        private readonly UsuarioApplication _usuarioApplication;
        private readonly EmailService _emailService;

        // Construtor do controlador
        public TarefaController(TarefaApplication tarefaApplication, UsuarioApplication usuarioApplication, EmailService emailService)
        {
            _tarefaApplication = tarefaApplication;
            _usuarioApplication = usuarioApplication;
            _emailService = emailService;
        }

        // Ação para exibir a página inicial do controlador
        public ActionResult Index()
        {
            return View();
        }

        // Ação para listar as tarefas
        public ActionResult ListaTarefas()
        {
            // Obtém o ID do perfil armazenado na sessão
            var idPerfilObj = Session["IdPerfil"];
            int? idPerfil = null;

            // Converte o ID do perfil para inteiro, se possível
            if (idPerfilObj != null)
            {
                int tempIdPerfil;
                if (int.TryParse(idPerfilObj.ToString(), out tempIdPerfil))
                {
                    idPerfil = tempIdPerfil;
                }
            }

            // Obtém a lista de tarefas
            var response = _tarefaApplication.GetTarefas();
            if (!response.Ok)
                return Error("Falha ao buscar Tarefas");

            IEnumerable<TarefaModel> tarefas = response.Content;

            // Filtra as tarefas com base no perfil do usuário, se necessário
            if (idPerfil.HasValue && idPerfil.Value == 0)
            {
                var userId = Session["Id"] as int?;
                if (userId.HasValue)
                {
                    tarefas = tarefas.Where(t => t.IdUsuario == userId.Value);
                }
            }

            // Retorna a visualização da lista de tarefas
            return View("_GridTarefas", tarefas);
        }

        // Ação para deletar uma tarefa
        public ActionResult Deletar(int id)
        {
            _tarefaApplication.Delete(id);
            TempData["tarefaexcluida"] = "Tarefa Excluida!";
            return RedirectToAction("ListaTarefas");
        }

        // Ação para marcar uma tarefa como concluída
        public ActionResult Concluir(int id)
        {
            // Primeiro, obtenha a tarefa que está sendo concluída.
            var tarefaResponse = _tarefaApplication.GetTarefas();
            if (!tarefaResponse.Ok)
                return Error("Falha ao buscar Tarefas");

            var tarefa = tarefaResponse.Content.FirstOrDefault(t => t.IdTarefa == id);
            if (tarefa == null)
                return Error("Tarefa não encontrada");

            // Marque a tarefa como concluída.
            _tarefaApplication.PutConcluirTarefa(id);

            // Recupere o usuário que criou a tarefa.
            var usuarioResponse = _usuarioApplication.GetUsuario(tarefa.CriadorId);
            if (!usuarioResponse.Ok)
                return Error("Falha ao buscar usuário");

            var usuario = usuarioResponse.Content;
            if (usuario == null)
                return Error("Usuário não encontrado");

            // Envie o e-mail para o criador da tarefa.
            var destinatario = usuario.Email; // E-mail do criador da tarefa
            var assunto = "Tarefa Concluída";
            var corpo = $"A tarefa '{tarefa.Descricao}' foi concluída.";

            _emailService.EnviarEmail(destinatario, assunto, corpo);

            TempData["MensagemConcluidoComSucesso"] = "Tarefa concluida com sucesso!";
            return RedirectToAction("ListaTarefas");
        }

        // Ação para exibir a página de adicionar uma nova tarefa
        public ActionResult Adicionar()
        {
            var usuariosResponse = _usuarioApplication.GetUsuarios();
            if (!usuariosResponse.Ok)
                return Error("Falha ao buscar usuários");

            var model = new TarefaModel
            {
                Usuario = usuariosResponse.Content
            };

            return View("AdicionarTarefa", model);
        }

        // Ação para adicionar uma nova tarefa
        [HttpPost]
        public ActionResult Post(TarefaModel tarefa)
        {
            var response = _tarefaApplication.Post(tarefa);
            if (!response.Ok)
                return Error("Falha ao inserir tarefa");

            // Buscar o usuário ao qual a tarefa foi atribuída
            var usuario = _usuarioApplication.GetUsuario(tarefa.IdUsuario);
            if (usuario == null)
                return Error("Usuário não encontrado.");

            // Enviar e-mail quando a tarefa for criada
            var destinatario = usuario.Content.Email; // Ajuste para o e-mail do usuário correto
            var assunto = "Nova Tarefa Criada";
            var corpo = $"A tarefa '{tarefa.Descricao}' foi atribuido a voce.";
            _emailService.EnviarEmail(destinatario, assunto, corpo);

            TempData["MensagemSucesso"] = "Tarefa cadastrada com sucesso!";

            return RedirectToAction("Index");
        }
    }
}

Pastel/Web/Pastelaria.Web/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Pastel/Web/Pastelaria.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"> @*responsaves de estilisar as tabelas*@
    <!-- FontAwesome CSS -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/Content/stylesMenu.css"> <!-- Certifique-se de que o caminho esteja correto -->
    <link rel="stylesheet" href="~/Content/Responsivo.css"> <!-- Certifique-se de que o caminho esteja correto -->
    
    <title>@ViewBag.Title</title>
</head>
<body>
    <!-- Menu lateral (sidebar) -->
    <nav id="sidebar">
        <div id="sidebar_content">
            <div id="user">
                <img src="~/Imagens/do-utilizador.png" id="user_avatar" alt="Usuario">
                <p id="user_infos">
                    <span class="item-description" style="font-size: 1.2em; font-weight: bold;">
                        @ViewBag.Username
                    </span>
                </p>
            </div>
            <ul id="side_items">
                <li class="side-item active">
                    <a href="@Url.Action("Index", "Home")">
                        <i class="fas fa-home"></i>
                        <span class="item-description">Home</span>
                    </a>
                </li>
                @if (ViewBag.IdPerfil == 1)
                {
                    <li class="side-item">
                        <a href="@Url.Action("Index", "Usuario")">
                            <i class="fa-solid fa-user"></i>
                            <span class="item-description">Usuários</span>
                        </a>
                    </li>
                }
                <li class="side-item">
                    <a href="@Url.Action("Index", "Tarefa")">
                        <i class="fas fa-tasks"></i>
                        <span class="item-description">Tarefas</span>
                    </a>
                </li>
                <li class="side-item">
                    <a href="@Url.Action("Index", "Sobre")">
                        <i class="fas fa-info-circle"></i>
                        <span class="item-description">Sobre</span>
                    </a>
                </li>
                <div id="logout">
                    <a id="logout_btn" href="@Url.Action("Index", "Login")">
                        <i class="fa-solid fa-right-from-bracket"></i>
                        <span class="item-description">Logout</span>
                    </a>
                </div>
            </ul>
            <button id="open_btn">
                <i id="open_btn_icon" class="fa-solid fa-chevron-right"></i>
            </button>
        </div>
    </nav>

    <main>
        <div class="container mt-4">
            @RenderBody()
        </div>
    </main>

    <script src="~/Scripts/scriptMenu.js"></script> <!-- Certifique-se de que o caminho esteja correto -->
</body>
</html>